version: '3.8'

services:
  discount-postgres:
    image: postgres
    container_name: discount-postgres
    read_only: true
    environment:
      - POSTGRES_USER=discount
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=discountDb
    expose:
      - "5432"  # PostgreSQL varsayılan portu
    ports:
      - "5477:5432"  # Dışarıdan 5477 portunu PostgreSQL 5432 portuna yönlendirme
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - discount-volume:/var/lib/postgresql/data

volumes:
  discount-volume:
