server:
  port: 6616

spring:
  datasource:
    url: jdbc:h2:mem:discountServerDB
    driverClassName: org.h2.Driver
    username: discount
    password: admin123
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
grpc:
  server:
    port: 9011


