server:
  port: 6616

spring:
  datasource:
    url: jdbc:postgresql://localhost:5477/discountDb
    username: discount
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  server:
    port: 9011


