server:
  port: 6616

spring:
  datasource:
    url: jdbc:postgresql://db-postgresql-nyc3-73636-do-user-15085525-0.c.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    username: doadmin
    password: AVNS_stifNfEMt8HX4SQKubH
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
grpc:
  server:
    port: 9011


